package kimgui.themes;

/**
 * DarkTheme for Kimgui.
 */
class DarkTheme {
  public static var theme: Theme = {
    TEXT_COLOR: 0xFFFFFFFF,
    TEXT_SIZE: 16,
    
    // Window properties
    WINDOW_BG_COLOR: 0xFF1E1E1E,
    WINDOW_BORDER_COLOR: 0xFF373737,
    WINDOW_BORDER_SIZE: 1.0,
    
    NODE_HIGHLIGHT_COLOR: 0xFF00508E,
    NODE_HIGHLIGHT_COLOR_ACTIVE: 0xFF0072B1,
    
    WINDOW_RESIZE_HANDLE_THICKNESS: 4.0,
    WINDOW_RESIZE_HANDLE_COLOR: 0xFF0072B1,
    
    WINDOW_TITLEBAR_TEXT_COLOR: 0xFFFFFFFF,
    WINDOW_TITLEBAR_COLOR: 0xFF003F6F,
    WINDOW_TITLEBAR_ACTIVE_COLOR: 0xFF00508E,
    WINDOW_TITLEBAR_HEIGHT: 20,
    WINDOW_TITLE_BAR_FONT_SIZE: 14,
    WINDOW_TITLE_BAR_PADDING: 3,

    ELEMENT_SPACING: 4,

    BUTTON_COLOR: 0xFF003F6F,
    BUTTON_HOVER_COLOR: 0xFF00508E,
    BUTTON_ACTIVE_COLOR: 0xFF0072B1,

    BUTTON_HEIGHT: 30,
    BUTTON_TEXT_COLOR: 0xFFFFFFFF,
    BUTTON_TEXT_SIZE: 16
  };
}