package kimgui.themes;

/**
 * DarkTheme for Kimgui.
 */
class DarkTheme {
  public static var theme: Theme = {
    TEXT_COLOR: 0xFFFFFFFF,
    TEXT_SIZE: 16,
    
    // Window properties
    NODE_HIGHLIGHT_COLOR: 0xFF00508E,
    NODE_HIGHLIGHT_COLOR_ACTIVE: 0xFF0072B1,
    
    WINDOW_BG_COLOR: 0xFF1E1E1E,
    WINDOW_BORDER_COLOR: 0xFF373737,
    WINDOW_BORDER_SIZE: 1.0,

    WINDOW_BODY_PADDING: 4,
    
    WINDOW_RESIZE_HANDLE_THICKNESS: 4.0,
    WINDOW_RESIZE_HANDLE_COLOR: 0xFF0072B1,
    
    WINDOW_TITLEBAR_TEXT_COLOR: 0xFFFFFFFF,
    WINDOW_TITLEBAR_COLOR: 0xFF003F6F,
    WINDOW_TITLEBAR_ACTIVE_COLOR: 0xFF00508E,
    WINDOW_TITLEBAR_HEIGHT: 20,
    WINDOW_TITLE_BAR_FONT_SIZE: 14,
    WINDOW_TITLE_BAR_PADDING: 3,

    // General Element properties
    ELEMENT_SPACING: 4,

    // Scrollbar properties
    SCROLL_SPEED: 4.0,
    SCROLLBAR_COLOR: 0xFF00508E,
    SCROLLBAR_THICKNESS: 4.0,

    // Button properties
    BUTTON_COLOR: 0xFF003F6F,
    BUTTON_HOVER_COLOR: 0xFF00508E,
    BUTTON_ACTIVE_COLOR: 0xFF0072B1,

    CHECKBOX_SIZE: 16,
    CHECKBOX_COLOR: 0xFFFFFFFF,
    CHECKBOX_CHECK_COLOR: 0xFF0072B1,
    CHECKBOX_PADDING: 2,

    BUTTON_HEIGHT: 30,
    BUTTON_TEXT_COLOR: 0xFFFFFFFF,
    BUTTON_TEXT_SIZE: 16
  };
}